# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Messaging'

target 'vroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for vroom
  # pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'BatchedBridge', # Required For React Native 0.45.0+
  #   'Core',
  #   # Add any other subspecs you want to use in your project
  #   'DevSupport',
  # ]
  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'vroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
