# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build a debug version of the app locally"
  lane :build do
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "development"
    )
    build_ios_app(
      workspace: "vroom.xcworkspace",
      scheme: "vroom",
      export_method: "development"
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
    #increment_build_number(xcodeproj: "vroom.xcodeproj")
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "appstore"
    )
    build_app(workspace: "vroom.xcworkspace", scheme: "vroom")
    upload_to_app_store
    #clean_build_artifacts
    #commit_version_bump(
    #  message: "Fastlane iOS: new prod build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
    #  xcodeproj: "vroom.xcodeproj",
    #  force: true
    #)
  end
  desc "Push a new beta build to TestFlight - internally"
  lane :beta_internal do
    increment_build_number(xcodeproj: "vroom.xcodeproj")
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "appstore"
    )
    build_app(workspace: "vroom.xcworkspace", scheme: "vroom")
    upload_to_testflight
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane iOS: new test build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
      xcodeproj: "vroom.xcodeproj",
      force: true
    )
  end
  desc "Push a new beta build to TestFlight - externally"
  lane :beta_external do
    increment_build_number(xcodeproj: "vroom.xcodeproj")
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "appstore"
    )
    build_app(workspace: "vroom.xcworkspace", scheme: "vroom")
    changelog = read_changelog(
      changelog_path: './../CHANGELOG.md'
    )
    upload_to_testflight(
      distribute_external: true,
      changelog: changelog
    )
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane iOS: new test build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
      xcodeproj: "vroom.xcodeproj",
      force: true
    )
  end
end
