# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "vroom.xcodeproj")
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "appstore"
    )
    build_app(workspace: "vroom.xcworkspace", scheme: "vroom")
    upload_to_app_store
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane iOS: new prod build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
      xcodeproj: "vroom.xcodeproj"
    )
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "vroom.xcodeproj")
    cocoapods
    match(
      git_url: "git@github.com:revitechnologies/vroom-certificates.git",
      type: "appstore"
    )
    build_app(workspace: "vroom.xcworkspace", scheme: "vroom")
    upload_to_testflight
    clean_build_artifacts
    commit_version_bump(
      message: "Fastlane iOS: new test build #{lane_context[SharedValues::BUILD_NUMBER]} [ci skip]",
      xcodeproj: "vroom.xcodeproj"
    )
  end
end
