# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end
  
  desc "Build a debug version of the app locally"
  lane :build do
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    gradle(task: "assembleDebug")
  end

  desc "Deploy a new internal testing build to Google Play Store"
  lane :test_internal do
    version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    gradle(task: "assembleRelease")
    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
    git_commit(
      path: "./app/build.gradle",
      message: "Fastlane Android: new internal build #{version_code} [ci skip]",
      force: true
    )
  end

  desc "Deploy a new external testing build to Google Play Store"
  lane :test_external do
    version_code = increment_version_code(
      gradle_file_path: "./app/build.gradle"
    )
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    gradle(task: "assembleRelease")
    supply(
      track: "beta",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
    git_commit(
      path: "./app/build.gradle",
      message: "Fastlane Android: new internal build #{version_code} [ci skip]",
      force: true
    )
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "assembleRelease")
  #   crashlytics
  #
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  desc "Deploy a new production build to Google Play Store"
  lane :deploy do
    yarn(
      command: "install",
      package_path: "../package.json"
    )
    gradle(task: "assembleRelease")
    upload_to_play_store
  end
end
